name: Scribd to PDF
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Scribd hujjat URL manzili'
        required: true
      pages:
        description: 'Necha sahifa kerak?'
        required: true
        default: '5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v3

      - name: Pythonni sozlash
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutubxonalarni o'rnatish
        run: |
          pip install selenium pillow

      - name: Skriptni ishga tushirish
        env:
          SCRIBD_URL: ${{ github.event.inputs.url }}
          PAGE_COUNT: ${{ github.event.inputs.pages }}
        run: python main.py

      - name: PDF-ni saqlab olish (Artifact)
        uses: actions/upload-artifact@v3
        with:
          name: scribd-pdf
          path: result.pdf
